{{- if .Values.calicoNetpol.enabled }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: {{ template "ingress.appName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  selector: dplane == 'ingress'
  types:
    - Ingress
    - Egress
  ingress:
    ### traffic from the load balancer ###
    - action: Allow
      protocol: TCP
      source: {{ toYaml .Values.calicoNetpol.subnetEntityRule | nindent 8 }}
      destination:
        ports: 
          {{- range .Values.service.ports }}
          - {{ .targetPort }}
          {{end }}
  egress:
    # allow to communicate to DNS pods
    - action: Allow
      protocol: UDP
      destination:
        namespaceSelector: projectcalico.org/name == 'kube-system'
        ports:
          - 53
    ### traffic to the inbound-worker ###
    - action: Allow
      protocol: TCP
      destination:
        selector: dplane == 'inbound-worker'
        namespaceSelector: projectcalico.org/name == '{{ .Release.Namespace }}'
    ### Traffic to the internet ###
    - action: Allow
      protocol: TCP
      destination: {{ toYaml .Values.calicoNetpol.outboundRule | nindent 8 }}
{{- end}}
