{{- if .Values.efs.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.global.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.persistence.claimAccessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.claimRequestCapacity }}
  volumeMode: Filesystem
  volumeName: {{ .Release.Namespace }}-{{ .Values.persistence.volumeName }}
{{- end -}}
