{{- if .Values.azfiles.enabled -}}


{{ $storageAccName := .Values.azfiles.azureStorageAccountName | required "Value azureStorageAccountName is required for the secret azurefs-secret" -}}
{{ $storageAccKey := .Values.azfiles.azureStorageAccountKey | required "Value azureStorageAccountKey is required for the secret azurefs-secret" -}}

apiVersion: v1
kind: Secret
metadata:
  name: "azurefs-secret"
type: "Opaque"
data:
  azurestorageaccountname: {{ $storageAccName | quote }}
  azurestorageaccountkey:  {{ $storageAccKey | quote }}

{{- end -}}
