{{- range  .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "a valid name is required" .name }}
type: {{  .type | default "Opaque" }}
data:
  {{- $secretName := .name -}}
    {{- range $key, $val := .data }}
    {{ $key }}: {{ required (printf "a valid %s is required for the secret %s" $key $secretName) (tpl $val $) | quote }}
    {{- end }}
{{- end }}