{{- if ne  (include "parent.dataplaneMode" . ) "shared" -}}

{{ $fromMailId := .Values.fromMailId | required "Value fromMailId is required for the secret ampint-frommail" -}}
{{ $fromMailPass := .Values.fromMailPassword | required "Value fromMailPassword is required for the secret ampint-frommail" -}}

apiVersion: v1
kind: Secret
metadata:
  name: "ampint-frommail"
type: "Opaque"
data:
  dxchange_email_frommailid: {{ $fromMailId | quote }}
  dxchange_email_frompassword:  {{ $fromMailPass | quote }}

{{- end -}}
