apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "predeploy.appName" . }}-cache-copy-{{ sha1sum .Values.image.buildTag | trunc 8 }}
  labels:
    ampint.ddplane: "cache-copy-job"
spec:
  template:
    metadata:
      labels:
        ampint.ddplane: "cache-copy-job"
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "predeploy.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.podSecurityContextEnabled }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.cacheCopy.enabled }}
        - name: cache-copy
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.buildTag }}"
          command:
            - "/bin/sh"
            - "-c"
            - >
              {{- if .Values.azureFiles.forceCloseHandles.enabled }}
              /bin/sh /predeploy-entrypoint-override.sh &&
              {{- else }}
              sh startup.sh &&
              {{- end }}
              mkdir -p /efs/transaction-data && mkdir -p /efs/transaction-logs && mkdir -p /efs/upgrade-check &&
              touch /efs/upgrade-check/cachecopy-complete-{{ .Values.image.buildTag }}.txt
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            {{- if eq (include "parent.dataplaneMode" . ) "shared" }}
            - name: is_shared
              value: "true"
            {{- end }}
          envFrom:
            - configMapRef:
                name: configmap-common
          volumeMounts:
            - name: {{ .Values.global.volumeStorageName }}
              mountPath: /efs
            - mountPath: /target
              name: target
            - mountPath: /tmp
              name: tmp
            {{- if .Values.azureFiles.forceCloseHandles.enabled }}
            - name: predeploy-entrypoint-override
              mountPath: /predeploy-entrypoint-override.sh
              subPath: predeploy-entrypoint-override.sh
            {{- end }}
      restartPolicy: Never
      volumes:
      - name: target
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      - name: {{ .Values.global.volumeStorageName }}
        persistentVolumeClaim:
          claimName: {{ .Release.Namespace }}-{{ .Values.global.claimName }}
      {{- if .Values.azureFiles.forceCloseHandles.enabled }}
      - name: predeploy-entrypoint-override
        configMap:
          name: predeploy-entrypoint-override.sh
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:  {{- toYaml . | nindent 8 }}
      {{- end }}
  backoffLimit: 3
{{- end -}}
