apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sink-agent.appName" . }}
  namespace: {{ .Release.Namespace }}
data:
  hazelcast_server_ip: hazelcast-{{ .Values.global.appEnv }}.{{ .Release.Namespace }}.svc.cluster.local
  environment: "{{ .Values.global.appEnv }}"
  JAVA_OPTS: "{{ .Values.javaOpts }}"