apiVersion: v1
kind: Service
metadata:
  name: {{ template "hazelcast.appName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hazelcast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hazelcast.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      protocol: {{ $port.protocol }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
    {{- end }}
