{{ if and .Values.serviceAccount.enabled .Values.podSecurityPolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ include "orchestrator.serviceAccountName" . }}-hostpath
roleRef:
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ include "orchestrator.serviceAccountName" . }}-hostpath
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "orchestrator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}