apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "orchestrator.appName" . }}
  namespace: {{ .Release.Namespace }}
data:
  kubernetes_service_name: {{ template "orchestrator.appName" . }}
  domain: "{{ .Values.global.appEnv }}.{{ .Values.global.external_domain }}"
  environment: {{ .Values.global.appEnv }}
  txn_log_base_path: "{{ .Values.hostPath.enabled | ternary .Values.txn_log_base_path .Values.efs_txn_log_path }}"
  ebs_root: "{{ .Values.hostPath.enabled | ternary .Values.ebs_root .Values.efs_root_path }}"
  hazelcast_server_ip: "hazelcast-{{ .Values.global.appEnv }}"
  JAVA_OPTS: "{{ .Values.javaOpts }}"
  orchestrator_service: "{{ .Chart.Name }}-{{ .Values.global.appEnv }}"
  max_executions_limit: "{{ .Values.max_executions_limit }}"
  enable_legacy_tls: "{{ .Values.enable_legacy_tls }}"
  k8_namespace: {{ .Release.Namespace }}
  stale_process_interval: "{{ .Values.stale_process_interval }}"
  QUARKUS_LOG_CONSOLE_LEVEL: "{{ .Values.QUARKUS_LOG_CONSOLE_LEVEL }}"
  max_payload_size_kbs: "{{ .Values.max_payload_size_kbs }}"
  heartbeat_time_interval_sec: "{{ .Values.heartbeat_time_interval_sec}}"
  heartbeat_timeout_sec: "{{ .Values.heartbeat_timeout_sec }}"
  {{- if .Values.cidr_range }}
  cidr_range: "{{ .Values.cidr_range }}"
  {{- end }}

