{{- if .Values.connectors.nfs.enabled }}
{{- range $index, $volume := .Values.connectors.nfs.volumes -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "ampint-connector-nfs-pvc-{{ $volume.name }}"
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: "{{ $.Release.Namespace }}-connector-nfs-pv-{{ $volume.name }}"
  resources:
    requests:
      storage: 2Gi
---
{{- end }}
{{- end }}