apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - appshe
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
