{{- if .Values.calicoNetpol.enabled }}
apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: {{ template "inbound-worker.appName" .}}
  namespace: {{ .Release.Namespace }}
spec:
  order: 10
  selector: dplane == 'inbound-worker'
  types:
    - Ingress
    - Egress
  ingress:
    ### traffic from inbound-worker & orchestrator,ingress###
    - action: Allow
      protocol: TCP
      source:
        selector: dplane == 'orchestrator' || dplane == 'inbound-worker' || dplane == 'ingress'
        namespaceSelector: projectcalico.org/name == '{{ .Release.Namespace }}'
      destination:
        ports:
          {{- range .Values.service.ports}}
          - {{ .targetPort }}
          {{- end}}
  egress:
    # allow to communicate to DNS pods
    - action: Allow
      protocol: UDP
      destination:
        namespaceSelector: projectcalico.org/name == 'kube-system'
        ports:
          - 53
    - action: Allow
      protocol: TCP
      destination:
        namespaceSelector: projectcalico.org/name == 'kube-system'
        ports:
          - 53
    ### Traffic to Hazelcast ###
    - action: Allow
      protocol: TCP
      destination:
        selector: dplane == 'hazelcast'
        namespaceSelector: projectcalico.org/name == '{{ .Release.Namespace }}'
    ### traffic to the orchestrator ###
    - action: Allow
      protocol: TCP
      destination:
        selector: dplane == 'orchestrator'
        namespaceSelector: projectcalico.org/name == '{{ .Release.Namespace }}'
    # allow to communicate with k8s api server
    - action: Allow
      destination:
        services:
          name: kubernetes
          namespace: default
      protocol: TCP
    ### Traffic to the internet ###
    - action: Allow
      protocol: TCP
      destination: {{ toYaml .Values.calicoNetpol.outboundRule | nindent 8 }}
{{- end}}
